[project]
name = "avm" # TODO: figure out the nested naming issue and change name after
version = "0.1.0"
source = "lib/include/kframework/avm"

[dependencies]
plugin = { path = "deps/" }
# kavm-hooks = { path = "hooks/" }

[targets.llvm]
backend = "llvm"
main-file = "avm-testing.md"
main-module = "AVM-TESTING"
syntax-module = "AVM-TESTING-SYNTAX"
md-selector = "k"
hook-namespaces = [ "KRYPTO", "KAVM" ]
emit-json = true
ccopts = [
    "{{ plugin:src }}/plugin_util.cpp",
    "{{ plugin:src }}/crypto.cpp",
    "{{ plugin:src }}/blake2.cpp",
    "-L{{ plugin:lib }}",
    "-I{{ plugin:include }}",
    "-lff",
    "-lcryptopp",
    "-lsecp256k1",
    "-lssl",
    "-lcrypto",
    "-lprocps",
    "-g",
    "-std=c++14",
]