[project]
name = "avm" # TODO: figure out the nested naming issue and change name after
version = "0.1.0"
source = "lib/include/kframework/avm"

[dependencies]
plugin = { path = "deps/" }
kavm-hooks = { path = "hooks/" }

[targets.llvm]
backend = "llvm"
main-file = "avm-testing.md"
main-module = "AVM-TESTING"
syntax-module = "AVM-TESTING-SYNTAX"
md-selector = "k"
hook-namespaces = [ "KRYPTO", "KAVM" ]
emit-json = true
ccopts = [
    "{{ plugin:src }}/plugin_util.cpp",
    "{{ plugin:src }}/crypto.cpp",
    "{{ plugin:src }}/blake2.cpp",
    "-L{{ plugin:lib }}",
    "-I{{ plugin:include }}",
    "-I/usr/include",
    "-lff",
    "-lcryptopp",
    "-lsecp256k1",
    "-lssl",
    "-lcrypto",
    "-lprocps",
    "-L/usr/lib",
    "-g",
    "-std=c++14",
    "{{ kavm-hooks:src }}/algorand.cpp",
    "{{ kavm-hooks:src }}/base.cpp",
    "{{ kavm-hooks:src }}/mnemonic.cpp",
    "{{ kavm-hooks:src }}/hooks.cpp",
    "-I{{ kavm-hooks:include }}",
]

[targets.haskell]
backend = "haskell"
main-file = "verification.k"
main-module = "VERIFICATION"
syntax-module = "VERIFICATION"
md-selector = "k"
hook-namespaces = [ "KRYPTO", "KAVM" ]
emit-json = true