[build-system]
requires = [
  "setuptools >= 51.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = "(venv-dev)"
target_version = ["py39"]
line-length = 88

[tool.isort]
py_version=39
skip = ["venv-dev", "venv-prod"]