from argparse import ArgumentParser

from pyk.cli_utils import dir_path, file_path

from .teal_to_k import teal_to_k


def main() -> None:
    parser = create_argument_parser()
    args = parser.parse_args()

    if args.command == 'teal-to-k':
        res = teal_to_k(args.definition_dir, args.contract_file)
        print(res)

    else:
        assert False


def create_argument_parser() -> ArgumentParser:
    parser = ArgumentParser(prog='kavm-pyk')
    command_parser = parser.add_subparsers(dest='command', required=True)

    teal_to_k_subparser = command_parser.add_parser(
        'teal-to-k', help='Output K definition for a given JSON output generated by the Teal compiler.'
    )
    teal_to_k_subparser.add_argument('definition_dir', type=dir_path, help='Path to definition to use.')
    teal_to_k_subparser.add_argument('contract_file', type=file_path, help='Path to contract JSON file.')

    return parser


if __name__ == "__main__":
    main()
