name: 'Master Push'
on:
  push:
    # branches:
    #   - master

jobs:
  nix-flake-release:
    name: 'Nix flake release'
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            os: ubuntu-latest
          - runner: macos-12
            os: macos-12
          - runner: MacM1
            os: self-macos-12
    runs-on: ${{ matrix.runner }}
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3

      - name: 'Upgrade bash'
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install bash

      - name: 'Install Nix/Cachix'
        if: ${{ !startsWith(matrix.os, 'self') }}
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = http://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - if: ${{ !startsWith(matrix.os, 'self') }}
        uses: cachix/cachix-action@v10
        with:
          name: k-framework
          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
          skipPush: true

      - name: 'Build and cache kavm'
        # uses: workflow/nix-shell-action@v3
        env:
          GC_DONT_GC: 1
          CACHIX_AUTH_TOKEN: '${{  secrets.CACHIX_PUBLIC_TOKEN }}'
          NIX_PATH: 'nixpkgs=http://nixos.org/channels/nixos-22.05/nixexprs.tar.xz'
        run: |
          export JQ=$(nix-build '<nixpkgs>' -A jq --no-link)/bin/jq
          kavm=$(nix build .#kavm --json | $JQ -r '.[].outputs | to_entries[].value')
          drv=$(nix-store --query --deriver ${kavm})
          nix-store --query --requisites --include-outputs ${drv} | cachix push k-framework
